### ISSUE TITLE
Error during loading of karma-jsdom-launcher on Windows 10

### ISSUE THREAD

**Issue by ghiscoding** [badeball/karma-jsdom-launcher#12]
I'm trying `karma-jsdom-launcher` for the first time and I'm getting the following error when starting karma:
```bash
Error during loading "C:\myProject\node_modules/karma-jsdom-launcher" plugin:
  Cannot find module 'jsdom'
```

If you look closely, this is due to the differences of slashes with Windows and Linux. The last slash is a forward slash `/`, while the two first ones are backward slash `\`. Users on Mac or Linux, probably don't see this.

Any other launchers, like `karma-phantomjs-launcher` or `karma-chrome-launcher` are working fine.

**Comment by badeball** [comment]
Have you installed `jsdom`? You have to do it manually (depending on your node version), as it is only listed as a peer dependency.

**Comment by ghiscoding** [comment]
Oh right, my bad, I didn't see your extra note under the installation. Thanks for the help and the package :)
