### ISSUE TITLE
Is it possible to inject "global" / "window" objects?

### ISSUE THREAD

**Issue by Janekk** [badeball/karma-jsdom-launcher#17]
I'd like to inject some parts of the DOM API to my jsdom instance, like [jsdom-global](https://github.com/rstacruz/jsdom-global) does, so that my jsdom test environement reflects the real broser better. Is it possible with karma-jsdom-launcher? Or do I have to switch to mocha in this case?

**Comment by corps** [comment]
Yes, try providing the `beforeParse` config to jsdomLauncher.

https://github.com/tmpvar/jsdom#intervening-before-parsing

```javascript
config.set({
   jsdomLauncher: {
     jsdom: {
       beforeParse: function(window) { ... }
    }
  }
});
```

**Comment by badeball** [comment]
Closed due to answered.
