### ISSUE TITLE
set userAgent invalid

### ISSUE THREAD

**Issue by leeziiAtCn** [badeball/karma-jsdom-launcher#26]
`
browsers: ['jsdom'],
    jsdomLauncher: {
      jsdom: {
        userAgent: 'asdasdasd'
      }
    },
`
i set userAgent as this, but i get jsdom default ua in test case , can u help me ?

**Comment by badeball** [comment]
Hi, @leeziiAtCn 

The way to change user agent with jsdom changed with the new API / deprecation of the old, in version 12. See below for how you would now control the user agent (Disclaimer: I typed this straight into Github without testing it). See jsdom's [own documentation](https://github.com/jsdom/jsdom/tree/12.0.0#advanced-configuration) for more information about configurating this.

```js
const jsdom = require("jsdom");

module.exports = function(config) {
  config.set({
    browsers: ['jsdom'],

    jsdomLauncher: {
      jsdom: {
        resources: new jsdom.ResourceLoader({
          userAgent: "foobar",
        })
      }
    }
  });
};
```

I'll update the readme to reflect this.

**Comment by leeziiAtCn** [comment]
@badeball 
hi bro , thanks for your help !
