### ISSUE TITLE
Karma 4 not supported as peer dependency

### ISSUE THREAD

**Issue by p4t5h3** [badeball/karma-jsdom-launcher#28]
The current release 7.0.0 from from 14th January does not yet support [Karma 4.0.0](https://github.com/karma-runner/karma/releases/tag/v4.0.0) which was released on January 23rd. This results in the following warning when working with`yarn`:

    warning " > karma-jsdom-launcher@7.0.0" has incorrect peer dependency "karma@^1.4.0 || ^2.0.0 || ^3.0.0".

**Comment by badeball** [comment]
Thank for the heads up. I've updated the peer dependencies and relased v7.1.0.
