### ISSUE TITLE
 Error during loading karma-jsdom-launcher

### ISSUE THREAD

**Issue by santarinto** [badeball/karma-jsdom-launcher#37]
Error during loading "/Users/<FAKE>/work/<FAKE>/node_modules/karma-jsdom-launcher" plugin:
  dlopen(/Users/<FAKE>/work/<FAKE>/node_modules/canvas/build/Release/canvas.node, 1): no suitable image found.  Did find:
	/Users/<FAKE>/work/<FAKE>/node_modules/canvas/build/Release/canvas.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/<FAKE>/work/<FAKE>/node_modules/canvas/build/Release/canvas.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

How can I solve this problem ?

**Comment by badeball** [comment]
Hi, @santarinto 

This doesn't appear to be an issue with the launcher, but rather an unrecognized executable in your node_module directory. Have you for example copied it from a different machine? Try re-installing everything, `npm ci`.

**Comment by badeball** [comment]
Closing as not an issue with the launcher itself.
