### ISSUE TITLE
Make jsdom a peer dependency

### ISSUE THREAD

**Issue by joscha** [badeball/karma-jsdom-launcher#9]
In order to allow which `jsdom` version is used, it would be great if `jsdom` itself could become a `peerDependency` instead of an actual one.

**Comment by badeball** [comment]
Absolutely. Thanks for pointing it out! I've made jsdom a peer dependency with 5.0.0. I've also added a simple smoke test and relaxed the version requirement to allow all the previously supported versions.

**Comment by joscha** [comment]
Nice, thank you!
